[options]
name = "outputs/test_"
track_trajectories = false
track_recoils = true
track_recoil_trajectories = false
write_buffer_size = 8000
weak_collision_order = 3
suppress_deep_recoils = false
high_energy_free_flight_paths = false
electronic_stopping_mode = "LOW_ENERGY_NONLOCAL"
mean_free_path_model = "LIQUID"
interaction_potential = [["KR_C"]]
scattering_integral = [["MENDENHALL_WELLER"]]
use_hdf5 = false
root_finder = [[{"NEWTON"={max_iterations=100, tolerance=1E-6}}]]
num_threads = 20
num_chunks = 10
track_displacements = false
track_energy_losses = false
angle_min = 0.02
angle_max = 0.98
angle_num = 97
x_min = 0.0
y_min = -0.1
z_min = -0.1
x_max = 0.1
y_max = 0.1
z_max = 0.1
x_num = 20
y_num = 20
z_num = 20

[particle_parameters]
length_unit = "ANGSTROM"
energy_unit = "EV"
mass_unit = "AMU"
N = [ 10000,]
m = [ 1.0079,]
Z = [ 1,]
E = [ 10,]
Ec = [ 1.0,]
Es = [ 0.0,]
interaction_index = [ 0 ]
pos = [ [ -1.75e-8, 0.0, 0.0,],]
dir = [ [ 0.999, 0.001, 0.0,], ]


[geometry_input]
length_unit = "ANGSTROM"
densities = [ [ 0.06133662, 0.01, 0.0,], [ 0.0, 0.0, 0.1143511,],]
layer_thicknesses = [1000, 10000]
electronic_stopping_correction_factors = [1.0, 1.0, 1.0]

[material_parameters]
energy_unit = "EV"
mass_unit = "AMU"
Eb = [ 0.0,0.0,3.0]
Es = [ 5.77,0.2,7.37]
Ec = [ 5.0,0.2,5.0]
Z = [ 5,8,6]
m = [ 10.811,16,12.011]
interaction_index = [0, 0, 0]
surface_binding_model = {"PLANAR"={calculation="TARGET"}}
bulk_binding_model = "AVERAGE"
